name: CI Sprint 1
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build images
        run: docker compose build

      - name: Start services
        run: |
          run: docker compose up -d dicom-gw rabbitmq ct-sim orthanc
          docker compose logs -f ct-sim | grep -m 1 "Study sent"

      - name: Verify RabbitMQ queue
        run: |
          pip install pika
          python -c "
          import pika, os
          connection = pika.BlockingConnection(pika.URLParameters('amqp://guest:guest@localhost:5672/%2F'))
          channel = connection.channel()
          queue = channel.queue_declare('new_study', passive=True)
          assert queue.method.message_count > 0, 'Queue empty!'
          connection.close()
          "

      - name: Run tests with coverage
        run: |
          docker compose exec gateway pytest --cov=gateway --cov-report=xml
          
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml