name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Prevents hanging jobs
    
    steps:
    - uses: actions/checkout@v4  # Updated from v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'  # Enable dependency caching
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r services/dicom-gw/requirements.txt
        
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 services/dicom-gw --count --show-source --statistics
        
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest tests --cov=services/dicom-gw --cov-report=xml
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml